import type { BlogPostDefinition, PostMeta } from "@/types/blog";

export const blogPostDefinitions = [
  {
    slug: "dev/centos8-mysql-delete",
    category: "dev",
    title: "CentOS8 MySQL 깨끗하게 삭제하기",
    date: "2021-08-31",
    description:
      "CentOS 8 환경에서 MySQL을 완전히 제거하고 잔여 설정 파일까지 정리하는 순서를 명령어와 함께 정리합니다.",
    tags: ["CentOS", "MySQL", "Linux", "Database", "DevOps"],
    readingTime: "2 min read",
    published: true,
    load: () => import("@/posts/dev/centos8-mysql-delete"),
  },
  {
    slug: "dev/centos8-mysql-install",
    category: "dev",
    title: "CentOS 8 MySQL 설정 기록과 안전한 계정 생성",
    date: "2021-09-04",
    description:
      "지원 종료된 CentOS 8 환경을 점검할 때 필요한 MySQL 상태 확인과 최소 권한 계정 생성 기준을 정리합니다.",
    tags: ["CentOS", "MySQL", "Linux", "Database", "Server"],
    readingTime: "5 min read",
    published: true,
    load: () => import("@/posts/dev/centos8-mysql-install"),
  },
  {
    slug: "dev/click-antigravity-workflow",
    category: "dev",
    title: "딸깍, 안티그래비티 워크플로우",
    date: "2025-12-21",
    description: "안티그래비티 워크플로우로 반복 작업 단순화 시키기",
    tags: ["Automation", "Workflow", "Productivity", "Antigravity"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/dev/click-antigravity-workflow"),
  },
  {
    slug: "dev/codepen-usage",
    category: "dev",
    title: "코드펜 사용하기",
    date: "2022-02-07",
    description:
      "CodePen의 기본 개념부터 가입, 에디터 사용법과 코드 공유 방식까지 프론트엔드 실습에 필요한 흐름을 정리합니다.",
    tags: ["CodePen", "Frontend", "HTML", "CSS", "JavaScript"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/codepen-usage"),
  },
  {
    slug: "dev/create-react-app-guide",
    category: "dev",
    title: "Create-React-App으로 React 시작하기.",
    date: "2020-11-13",
    description:
      "create-react-app으로 리액트 프로젝트를 시작하는 준비 단계와 설치, 실행 과정을 초보자 기준으로 정리합니다.",
    tags: ["React", "Create React App", "JavaScript", "Frontend", "Getting Started"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/create-react-app-guide"),
  },
  {
    slug: "dev/git-basic-commands",
    category: "dev",
    title: "Git 기본 명령어: 작업 흐름 마스터하기",
    date: "2025-12-19",
    description:
      "Git의 가장 기초적이면서도 필수적인 명령어인 init, status, add, commit, push, pull을 완벽하게 이해하고 작업 흐름을 마스터해봅시다.",
    tags: ["Git", "Basics", "Tutorial"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/git-basic-commands"),
  },
  {
    slug: "dev/git-branch-commands",
    category: "dev",
    title: "Git 브랜치 전략: 협업을 위한 필수 명령어",
    date: "2025-12-19",
    description:
      "Git의 강력한 기능인 Branch를 활용하는 방법과 협업 시 필수적인 merge, checkout, log 등의 명령어를 알아봅니다.",
    tags: ["Git", "Branch", "Collaboration"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/git-branch-commands"),
  },
  {
    slug: "dev/github-token-auth",
    category: "dev",
    title: "Github 토큰 인증",
    date: "2021-08-17",
    description:
      "GitHub 비밀번호 인증 종료 이후 Personal Access Token을 발급하고 원격 저장소 인증에 적용하는 방법을 정리합니다.",
    tags: ["GitHub", "Git", "Authentication", "Token", "PAT"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/github-token-auth"),
  },
  {
    slug: "dev/html-mistakes-1",
    category: "dev",
    title: "쉽게 놓치고 지나갈 수 있는 실수 정리 : HTML (1)",
    date: "2021-09-01",
    description:
      "사이드 프로젝트에서 겪은 HTML 경고 사례를 바탕으로 body 시멘틱과 input autocomplete 같은 놓치기 쉬운 포인트를 정리합니다.",
    tags: ["HTML", "Accessibility", "Semantic HTML", "Autocomplete", "Web"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/dev/html-mistakes-1"),
  },
  {
    slug: "dev/introducing-skills-to-antigravity",
    category: "dev",
    title: "드디어 안티그래비티에 스킬스가 추가되었습니다.",
    date: "2026-01-19",
    description:
      "안티그래비티의 새로운 기능, 'Skills'를 소개합니다. 에이전트의 능력을 확장하고 복잡한 작업을 효율적으로 처리하는 방법을 알아보세요.",
    tags: ["Antigravity", "Skills", "Agent", "Productivity"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/dev/introducing-skills-to-antigravity"),
  },
  {
    slug: "dev/javascript-age-calculation",
    category: "dev",
    title: "JavaScript 만나이 계산",
    date: "2022-04-12",
    description:
      "JavaScript로 만나이를 계산하는 로직을 예제 코드와 함께 설명하고 날짜 비교 시 주의할 점을 정리합니다.",
    tags: ["JavaScript", "Date", "Age Calculation", "Algorithm", "CodePen"],
    readingTime: "2 min read",
    published: true,
    load: () => import("@/posts/dev/javascript-age-calculation"),
  },
  {
    slug: "dev/javascript-array-reduce",
    category: "dev",
    title: "Javascript Array.Reduce",
    date: "2023-02-07",
    description:
      "Array.prototype.reduce의 동작 원리와 누적값 패턴을 간단한 예제로 풀어보며 실전 활용 방법을 정리합니다.",
    tags: ["JavaScript", "Array", "Reduce", "Functional Programming", "ES6"],
    readingTime: "5 min read",
    published: true,
    load: () => import("@/posts/dev/javascript-array-reduce"),
  },
  {
    slug: "dev/javascript-last-day-of-month",
    category: "dev",
    title: "JavaScript 매달 마지막 날 계산",
    date: "2022-06-29",
    description:
      "Date 객체를 활용해 월별 마지막 날짜를 간단히 구하는 방법과 코드 해석 포인트를 정리합니다.",
    tags: ["JavaScript", "Date", "Calendar", "Algorithm", "CodePen"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/javascript-last-day-of-month"),
  },
  {
    slug: "dev/kotlin-ios-development",
    category: "dev",
    title: "Kotlin으로 iOS 개발이 가능??",
    date: "2020-11-11",
    description:
      "Kotlin/Native를 계기로 Kotlin이 안드로이드 외 iOS 및 멀티플랫폼 개발에 활용되는 흐름을 살펴본 메모입니다.",
    tags: ["Kotlin", "iOS", "Kotlin Native", "Mobile", "Cross Platform"],
    readingTime: "1 min read",
    published: true,
    load: () => import("@/posts/dev/kotlin-ios-development"),
  },
  {
    slug: "dev/node-env-vars",
    category: "dev",
    title: "node 환경 변수 설정하기",
    date: "2021-08-24",
    description:
      "Windows 환경에서 Node 명령어가 동작하지 않을 때 PATH 환경 변수를 확인하고 설정하는 과정을 정리합니다.",
    tags: ["Node.js", "Environment Variables", "Windows", "PATH", "Troubleshooting"],
    readingTime: "2 min read",
    published: true,
    load: () => import("@/posts/dev/node-env-vars"),
  },
  {
    slug: "dev/postman-api-test",
    category: "dev",
    title: "REAT API 테스트 툴 POSTMAN",
    date: "2021-09-10",
    description:
      "REST API 테스트 도구 Postman 설치부터 요청 작성과 응답 확인까지 기본 사용 흐름을 예제로 정리합니다.",
    tags: ["Postman", "API", "REST", "Backend", "Testing"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/postman-api-test"),
  },
  {
    slug: "dev/putty-install-guide",
    category: "dev",
    title: "Putty 설치 및 사용방법",
    date: "2020-11-16",
    description:
      "PuTTY의 개념과 설치 방법, 원격 접속 프로토콜(SSH/Telnet 등) 기초를 초보자 관점에서 정리합니다.",
    tags: ["PuTTY", "SSH", "Remote Desktop", "Windows", "Network"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/dev/putty-install-guide"),
  },
  {
    slug: "dev/react-nextjs-security-2025",
    category: "dev",
    title: "React&Next.js 보안 이슈: React2Shell 대응",
    date: "2025-12-11",
    description:
      "React Server Components 취약점 대응을 위해 영향을 확인하고 패치·검증하는 절차를 정리합니다.",
    tags: ["Security", "React", "Next.js", "CVE"],
    readingTime: "6 min read",
    published: true,
    load: () => import("@/posts/dev/react-nextjs-security-2025"),
  },
  {
    slug: "dev/scss-pros-cons-usage",
    category: "dev",
    title: "SCSS 사용하는 이유, SCSS 장점과 실 사용 예제",
    date: "2021-09-15",
    description:
      "SCSS를 도입하는 이유와 장점, 그리고 중첩·변수·믹스인 등 실무에서 자주 쓰는 문법 예제를 정리합니다.",
    tags: ["SCSS", "CSS", "Frontend", "Styling", "Sass"],
    readingTime: "10 min read",
    published: true,
    load: () => import("@/posts/dev/scss-pros-cons-usage"),
  },
  {
    slug: "dev/setstate-rerender-issue",
    category: "dev",
    title: "setState로 리렌더링이 안 되는 이유..",
    date: "2021-09-22",
    description:
      "React에서 setState를 호출했는데 리렌더링되지 않던 원인을 참조형 상태 업데이트 관점에서 정리한 트러블슈팅 글입니다.",
    tags: ["React", "setState", "Rerender", "State Management", "Troubleshooting"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/setstate-rerender-issue"),
  },
  {
    slug: "dev/typescript-express-login-1",
    category: "dev",
    title: "TypeScript, Express-session 을 이용한 로그인 처리 (1)",
    date: "2021-09-08",
    description:
      "TypeScript와 Express-session 기반 로그인 구현의 1편으로 개념과 초기 세팅 과정을 다룹니다.",
    tags: ["TypeScript", "Express", "Session", "Login", "Backend"],
    readingTime: "5 min read",
    published: true,
    load: () => import("@/posts/dev/typescript-express-login-1"),
  },
  {
    slug: "dev/typescript-express-login-2",
    category: "dev",
    title: "TypeScript, Express-session 을 이용한 로그인 처리 (2)",
    date: "2021-09-11",
    description:
      "TypeScript와 Express-session 로그인 구현 2편으로 SessionData 타입 확장과 로그인 처리 로직을 정리합니다.",
    tags: ["TypeScript", "Express", "Session", "Authentication", "Login"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/typescript-express-login-2"),
  },
  {
    slug: "dev/typescript-express-login-3",
    category: "dev",
    title: "TypeScript, Express-session 을 이용한 로그인 처리 (3)",
    date: "2021-09-18",
    description:
      "TypeScript와 Express-session 로그인 구현 3편으로 쿠키를 이용한 자동 로그인 처리 방법을 정리합니다.",
    tags: ["TypeScript", "Express", "Cookie", "Session", "Auto Login"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/typescript-express-login-3"),
  },
  {
    slug: "dev/typescript-express-setup",
    category: "dev",
    title: "TypeScript로 Express 서버 시작하기",
    date: "2021-08-22",
    description:
      "지원 중인 Node.js와 tsx를 기준으로 TypeScript Express 서버를 구성하는 방법을 정리합니다.",
    tags: ["TypeScript", "Express", "Node.js", "Backend", "Setup"],
    readingTime: "10 min read",
    published: true,
    load: () => import("@/posts/dev/typescript-express-setup"),
  },
  {
    slug: "dev/typescript-react-express-integration",
    category: "dev",
    title: "TypeScript를 사용한 React를 기존 Express 서버에 올리기",
    date: "2021-08-28",
    description:
      "기존 Express 서버에 TypeScript React 앱을 올리고 concurrently로 개발 서버를 함께 운영하는 방법을 정리합니다.",
    tags: ["TypeScript", "React", "Express", "Integration", "Concurrently"],
    readingTime: "6 min read",
    published: true,
    load: () => import("@/posts/dev/typescript-react-express-integration"),
  },
  {
    slug: "dev/useful-sites-for-design-1",
    category: "dev",
    title: "반드시 필요하진 않지만, 알아두면 유용한 사이트 정보 (1)",
    date: "2021-08-02",
    description:
      "개발·디자인 작업 시 알아두면 유용한 웹사이트들을 기능별로 소개하고 활용 포인트를 정리합니다.",
    tags: ["Design Tools", "Developer Tools", "Resources", "Web", "Productivity"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/useful-sites-for-design-1"),
  },
  {
    slug: "dev/useful-sites-for-design-2",
    category: "dev",
    title: "반드시 필요하진 않지만, 알아두면 유용한 사이트 정보 (2)",
    date: "2021-08-25",
    description:
      "화면 설계와 디자인 작업에 도움이 되는 색상·아이콘·템플릿 사이트를 중심으로 유용한 링크를 정리합니다.",
    tags: ["Design", "UI", "Color", "Icons", "Resources"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/useful-sites-for-design-2"),
  },
  {
    slug: "dev/what-is-knip",
    category: "dev",
    title: "Knip은 뭘까?",
    date: "2025-12-21",
    description: "코드 깔끔쟁이 들을 위한 라이브러리",
    tags: ["Knip", "Tooling", "Cleanup", "Refactoring"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/dev/what-is-knip"),
  },
  {
    slug: "dev/why-not-momentjs",
    category: "dev",
    title: "moment.js를 사용하면 안 될 이유",
    date: "2023-03-06",
    description:
      "moment.js가 레거시로 전환된 배경을 정리하고 대안으로 Luxon을 선택해 사용하는 이유와 예제를 소개합니다.",
    tags: ["JavaScript", "moment.js", "Luxon", "Date", "Library Migration"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/why-not-momentjs"),
  },
  {
    slug: "dev/window-vs-document",
    category: "dev",
    title: "window 와 document 차이",
    date: "2022-07-16",
    description:
      "브라우저 환경에서 window와 document의 관계를 콘솔 예제로 확인하며 차이를 간단히 정리합니다.",
    tags: ["JavaScript", "Browser", "window", "document", "DOM"],
    readingTime: "3 min read",
    published: true,
    load: () => import("@/posts/dev/window-vs-document"),
  },
  {
    slug: "dev/window-web-api",
    category: "dev",
    title: "쓰려고 하면 기억 안 나는 Window Web Api",
    date: "2022-06-08",
    description:
      "자주 잊기 쉬운 window Web API들을 예제와 함께 정리해 반응형 처리와 스크롤 제어에 바로 쓸 수 있게 정리합니다.",
    tags: ["JavaScript", "Web API", "window", "Responsive", "Scroll"],
    readingTime: "5 min read",
    published: true,
    load: () => import("@/posts/dev/window-web-api"),
  },
  {
    slug: "dev/windows-rdp-guide",
    category: "dev",
    title: "[Windows] RDP (원격 데스크톱 사용방법)",
    date: "2020-11-12",
    description:
      "Windows 원격 데스크톱(RDP)의 개념과 설정, 실제 접속 절차를 처음 사용하는 사람 기준으로 정리합니다.",
    tags: ["Windows", "RDP", "Remote Desktop", "Network", "Guide"],
    readingTime: "4 min read",
    published: true,
    load: () => import("@/posts/dev/windows-rdp-guide"),
  },
  {
    slug: "journal/fixing-routing-redirects",
    category: "journal",
    title: "Next.js 라우팅 트러블슈팅: URL vs 로컬 스토리지",
    date: "2025-12-21",
    description:
      "로컬 스토리지 기반의 히스토리 탭 기능을 구현하면서 겪은 강제 리다이렉트 문제와 이를 해결하기 위해 URL을 진실의 원천(Source of Truth)으로 변경한 과정을 공유합니다.",
    tags: ["Next.js", "Routing", "Troubleshooting", "UX"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/journal/fixing-routing-redirects"),
  },
  {
    slug: "journal/galaxy-tab-never-dies",
    category: "journal",
    title: "갤럭시탭 넌 죽지못해",
    date: "2026-01-03",
    description: "termux활용하여 유휴 갤럭시탭 서버로 활용하기",
    tags: ["termux", "android", "galaxy-tab", "home-server", "재활용"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/journal/galaxy-tab-never-dies"),
  },
  {
    slug: "journal/game-dev-log",
    category: "journal",
    title: "Sky Drop 게임 제작기: React와 Phaser의 만남",
    date: "2025-12-19",
    description:
      "React 환경에서 Phaser를 이용해 'Sky Drop' 게임을 개발하며 겪은 시행착오와 개선 기록. 렌더링 이슈부터 반응형 디자인, 그리고 재미 요소를 더하기까지의 여정을 공유합니다.",
    tags: ["Game Dev", "Phaser", "React", "Retrospective"],
    readingTime: "7 min read",
    published: true,
    load: () => import("@/posts/journal/game-dev-log"),
  },
  {
    slug: "journal/game-ux-improvement",
    category: "journal",
    title: "플레이 경험을 완성하는 디테일: Sky Drop UX 개선",
    date: "2025-12-24",
    description:
      "게임의 핵심 로직만큼이나 중요한 것이 바로 사용자 경험(UX)입니다. Sky Drop 게임을 플레이하면서 느꼈던 불편함을 해소하고, 더 몰입감 있는 환경을 만들기 위해 진행했던 UX 개선 작업을 기록합니다.",
    tags: ["Game Dev", "UX", "Sky Drop", "Polishing"],
    readingTime: "5 min read",
    published: true,
    load: () => import("@/posts/journal/game-ux-improvement"),
  },
  {
    slug: "journal/guido-van-rossum-microsoft",
    category: "journal",
    title: "귀도 반 로섬, 파이썬 창시자의 이직",
    date: "2020-11-16",
    description:
      "파이썬 창시자 귀도 반 로섬의 Microsoft 합류 소식을 정리하고 개발 생태계 관점에서 의미를 간단히 기록합니다.",
    tags: ["Python", "Guido van Rossum", "Microsoft", "Tech News", "Journal"],
    readingTime: "2 min read",
    published: true,
    load: () => import("@/posts/journal/guido-van-rossum-microsoft"),
  },
  {
    slug: "journal/hello-world",
    category: "journal",
    title: "블로그를 시작하며",
    date: "2024-12-13",
    description: "MDX로 구현한 블로그의 첫 번째 포스트입니다.",
    tags: ["블로그", "Next.js", "MDX"],
    readingTime: "1 min read",
    published: true,
    load: () => import("@/posts/journal/hello-world"),
  },
  {
    slug: "journal/journey-to-increase-game-users",
    category: "journal",
    title: "게임 유저를 늘리기위한 여정 (기능 구현부터 OG 삽질까지)",
    date: "2025-12-25",
    description:
      "Sky Drop 게임의 공유 기능을 만들며 겪었던 기능 구현, 버그 수정, 그리고 Next.js OG Image의 기술적 한계와 디자인 시행착오에 대한 생생한 기록입니다.",
    tags: ["game-dev", "dev-log", "nextjs", "opengraph", "debugging"],
    readingTime: "5 min read",
    published: true,
    load: () => import("@/posts/journal/journey-to-increase-game-users"),
  },
  {
    slug: "journal/resume-rag-chat-design-decisions",
    category: "journal",
    title: "이력서 RAG 채팅을 만들며 정리한 구조와 고민",
    date: "2026-07-06",
    description:
      "개인 이력서에 질문할 수 있는 RAG 채팅을 만들면서 벡터 DB, 텍스트 검색, Codex app-server, 공개 채팅 보안, 실패 UI를 어떻게 나눠 생각했는지 기록합니다.",
    tags: ["RAG", "Architecture", "Codex", "NestJS", "Next.js", "UX"],
    readingTime: "17 min read",
    published: true,
    load: () => import("@/posts/journal/resume-rag-chat-design-decisions"),
  },
  {
    slug: "journal/sidebar-ux-improvements",
    category: "journal",
    title: "사이드바 UX 개선기: 가독성, 페이지네이션, 그리고 검색까지",
    date: "2025-12-21",
    description:
      "사이드바의 가독성을 개선하고 페이지네이션을 구현한 후, 블로그 대시보드에 검색 및 자동완성 기능을 추가한 과정을 기록합니다.",
    tags: ["Next.js", "UX", "Pagination", "Sidebar", "Search", "Debounce", "Refactoring"],
    readingTime: "9 min read",
    published: true,
    load: () => import("@/posts/journal/sidebar-ux-improvements"),
  },
  {
    slug: "journal/wiki-mcp-for-designers",
    category: "journal",
    title: "코드 저장소 밖의 동료를 위해 Wiki MCP를 만든 기록",
    date: "2026-08-01",
    description:
      "개발팀의 저장소 지식을 디자이너도 Claude에서 활용할 수 있도록 Markdown 기반 읽기 전용 Wiki MCP를 설계하고 서버에 올린 과정을 기록합니다.",
    tags: ["MCP", "Markdown", "Knowledge Management", "AI", "Retrospective"],
    readingTime: "10 min read",
    published: true,
    load: () => import("@/posts/journal/wiki-mcp-for-designers"),
  },
] satisfies BlogPostDefinition[];

const definitionsBySlug = new Map(
  blogPostDefinitions.map(definition => [definition.slug, definition]),
);

export const getBlogPostDefinition = (slug: string): BlogPostDefinition | null => {
  return definitionsBySlug.get(slug) ?? null;
};

export const getRegisteredPostMetas = (): PostMeta[] => {
  return blogPostDefinitions.map(definition => ({
    slug: definition.slug,
    category: definition.category,
    title: definition.title,
    date: definition.date,
    description: definition.description,
    tags: [...definition.tags],
    readingTime: definition.readingTime,
    published: definition.published,
  }));
};
