export const ArrowDriftConstants = {
  MAX_WIDTH: 480,
  ASPECT_RATIO_CSS: "9/16",
  ARROW_COLOR: 0xc1121f,
  ARROW_TRAIL_COLOR: 0x38bdf8,
  ARROW_SPEED: 260,
  SCORE_PER_OBSTACLE: 100,
  ARROW_HITBOX_WIDTH: 24,
  ARROW_HITBOX_HEIGHT: 10,
  BASE_OBSTACLE_SPEED: 253,
  BASE_VERTICAL_PADDING: 16,
  DIFFICULTY: {
    SPEED_STEP_INTERVAL_MS: 15000,
    SPEED_MULTIPLIER_PER_STEP: 1.12,
    MAP_SHRINK_INTERVAL_MS: 30000,
    MAP_SHRINK_PER_STEP: 12,
    MAP_SHRINK_MAX: 120,
  },
  OBSTACLE: {
    TEXTURE_SIZE: 96,
    PRESET_TEXTURE_KEYS: [
      "ad-obstacle-0",
      "ad-obstacle-1",
      "ad-obstacle-2",
      "ad-obstacle-3",
      "ad-obstacle-4",
      "ad-obstacle-5",
      "ad-obstacle-6",
    ],
    SPAWN_SIDE_OFFSET: 44,
    SPAWN_VERTICAL_MARGIN: 8,
    SCALE_X_MIN: 0.72,
    SCALE_X_MAX: 1.28,
    SCALE_Y_MIN: 0.62,
    SCALE_Y_MAX: 1.36,
    SPEED_FACTOR_MIN: 0.8,
    SPEED_FACTOR_MAX: 1.2,
    HITBOX_CORE_SCALE: 0.62,
  },
  ITEM: {
    STAR_VARIANTS: [
      {
        key: "ad-item-score-gold",
        assetPath: "/images/game/arrow-drift/score-star.svg",
        score: 140,
        weight: 42,
      },
      {
        key: "ad-item-score-emerald",
        assetPath: "/images/game/arrow-drift/score-star-emerald.svg",
        score: 220,
        weight: 28,
      },
      {
        key: "ad-item-score-sapphire",
        assetPath: "/images/game/arrow-drift/score-star-sapphire.svg",
        score: 320,
        weight: 17,
      },
      {
        key: "ad-item-score-violet",
        assetPath: "/images/game/arrow-drift/score-star-violet.svg",
        score: 440,
        weight: 9,
      },
      {
        key: "ad-item-score-ruby",
        assetPath: "/images/game/arrow-drift/score-star-ruby.svg",
        score: 620,
        weight: 4,
      },
    ],
    DEFAULT_SCORE: 140,
    SPAWN_SIDE_OFFSET: 40,
    SPAWN_VERTICAL_MARGIN: 14,
    SCALE_MIN: 0.78,
    SCALE_MAX: 1.12,
    SPEED_FACTOR_MIN: 0.92,
    SPEED_FACTOR_MAX: 1.24,
    HITBOX_CORE_SCALE: 0.68,
    SPIN_SPEED_MIN: -90,
    SPIN_SPEED_MAX: 90,
  },
  SPAWN: {
    INITIAL_GRACE_MS: 1600,
    WAVE_DELAY_START_MIN_MS: 1900,
    WAVE_DELAY_START_MAX_MS: 3200,
    WAVE_DELAY_MIN_MS: 820,
    WAVE_DELAY_MAX_MS: 1700,
    WAVE_DELAY_RAMP_MS: 75000,
    IN_WAVE_GAP_MIN_MS: 130,
    IN_WAVE_GAP_MAX_MS: 280,
    DOUBLE_WAVE_CHANCE_START: 0.04,
    DOUBLE_WAVE_CHANCE_END: 0.32,
    TRIPLE_WAVE_CHANCE_START: 0.0,
    TRIPLE_WAVE_CHANCE_END: 0.12,
    MULTI_WAVE_RAMP_MS: 70000,
    FORMATION_STEP_MIN: 72,
    FORMATION_STEP_MAX: 140,
    ITEM_CHANCE_START: 0.22,
    ITEM_CHANCE_END: 0.45,
    ITEM_CHANCE_RAMP_MS: 70000,
  },
  BACKGROUND_SCROLL: {
    FAR_FACTOR: 0.25,
    NEAR_FACTOR: 0.55,
  },
};
