/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["GameController_createResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/ranking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GameController_getRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GameController_getGameResult"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateGameHistoryDto: {
      score: number;
      playTime?: number;
      /** @enum {string} */
      gameType: "BLOCK_TOWER" | "SKY_DROP";
    };
    GameHistoryUserDto: {
      /**
       * @description 사용자 닉네임
       * @example 홍길동
       */
      displayName: string;
    };
    GameHistoryResponseDto: {
      /**
       * @description 게임 기록 ID (UUID)
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 게임 타입
       * @example BLOCK_TOWER
       * @enum {string}
       */
      gameType: "BLOCK_TOWER" | "SKY_DROP";
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
      /**
       * @description 현재 등수 (1부터 시작, 랭킹 외 시 null)
       * @example 1
       */
      rank?: number | null;
    };
    User: {
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      accessToken: string;
    };
    GameHistory: {
      id: string;
      score: number;
      /** @enum {string} */
      gameType: "BLOCK_TOWER" | "SKY_DROP";
      /** Format: date-time */
      createdAt: string;
      userId: string;
      user: components["schemas"]["User"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  GameController_createResult: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameHistoryDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
    };
  };
  GameController_getRanking: {
    parameters: {
      query: {
        gameType: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistory"][];
        };
      };
    };
  };
  GameController_getGameResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공유된 게임 결과 조회 (로그인 필요 없음) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
    };
  };
}
