/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 서버 상태 확인 */
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 게임 결과 생성 및 랭킹 확인 */
    post: operations["GameController_createResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/ranking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 게임별 Top 10 랭킹 조회 */
    get: operations["GameController_getRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 게임 결과 상세 조회 */
    get: operations["GameController_getGameResult"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wordle/word": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 랜덤 5글자 단어 조회 */
    get: operations["WordleController_getRandomWord"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wordle/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 단어 유효성 검사 */
    post: operations["WordleController_checkWord"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateGameHistoryDto: {
      score: number;
      playTime?: number;
      /** @enum {string} */
      gameType: "SKY_DROP";
    };
    GameHistoryUserDto: {
      /**
       * @description 사용자 닉네임
       * @example 홍길동
       */
      displayName: string;
    };
    GameHistoryResponseDto: {
      /**
       * @description 게임 기록 ID (UUID)
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 게임 타입
       * @example SKY_DROP
       * @enum {string}
       */
      gameType: "SKY_DROP";
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
      /**
       * @description 현재 등수 (1부터 시작, 랭킹 외 시 null)
       * @example 1
       */
      rank?: number | null;
      /**
       * @description 유저의 역대 최고 점수
       * @example 1200
       */
      bestScore?: number | null;
      /**
       * @description 전체 기간 랭킹
       * @example 42
       */
      allTimeRank?: number | null;
      /**
       * @description 금주 랭킹 (KST 월요일 0시 ~ 일요일 24시 기준)
       * @example 5
       */
      weeklyRank?: number | null;
    };
    User: {
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      accessToken: string;
    };
    GameHistory: {
      id: string;
      score: number;
      /** @enum {string} */
      gameType: "SKY_DROP";
      /** Format: date-time */
      createdAt: string;
      userId: string;
      user: components["schemas"]["User"];
    };
    WordResponseDto: {
      /**
       * @description 5글자 영단어
       * @example apple
       */
      word: string;
    };
    CheckWordDto: {
      /**
       * @description 확인할 5글자 영단어
       * @example apple
       */
      word: string;
    };
    CheckWordResponseDto: {
      /**
       * @description 단어 존재 여부
       * @example true
       */
      exists: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 서버가 정상적으로 동작 중임을 나타내는 메시지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  GameController_createResult: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameHistoryDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
    };
  };
  GameController_getRanking: {
    parameters: {
      query: {
        gameType: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistory"][];
        };
      };
    };
  };
  GameController_getGameResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공유된 게임 결과 조회 (로그인 필요 없음) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
    };
  };
  WordleController_getRandomWord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 랜덤으로 선택된 5글자 영단어 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WordResponseDto"];
        };
      };
    };
  };
  WordleController_checkWord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckWordDto"];
      };
    };
    responses: {
      /** @description 단어 존재 여부 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckWordResponseDto"];
        };
      };
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckWordResponseDto"];
        };
      };
    };
  };
}
