type ResumeRagKeywordGroup = {
  id: string;
  weight: number;
  aliases: readonly string[];
};

const MIN_RESUME_RAG_KEYWORD_SCORE = 2;

export const RESUME_RAG_KEYWORD_GROUPS: readonly ResumeRagKeywordGroup[] = [
  {
    id: 'oprimed',
    weight: 3,
    aliases: ['oprimed', 'optivis', '오프리메드', '오프리', '오프티비스'],
  },
  {
    id: 'company-code-crayon',
    weight: 3,
    aliases: [
      'code crayon',
      'codecrayon',
      '코드크레용',
      'sellectors',
      '셀렉터스',
      'shortime',
      '숏타임',
      '쇼타임',
    ],
  },
  {
    id: 'company-allofthem',
    weight: 3,
    aliases: ['all of them', 'allofthem', '올오브뎀', 'aig'],
  },
  {
    id: 'company-datalogics',
    weight: 3,
    aliases: ['datalogics', '데이터로직스', '국무조정실'],
  },
  {
    id: 'healthcare-domain',
    weight: 3,
    aliases: [
      '의료',
      '임상',
      '환자',
      '질병',
      '약물',
      '검사',
      'healthcare',
      'clinical',
      'patient',
      'clinical background',
      'tsi',
      'trp',
      'drd',
      'ats',
    ],
  },
  {
    id: 'frontend',
    weight: 2,
    aliases: [
      '프론트엔드',
      'frontend',
      'react',
      'next.js',
      'nextjs',
      'typescript',
      '상태관리',
      'ui',
      'hook',
      'component',
      '컴포넌트',
      '브라우저',
      'css',
      'sass',
      'swr',
      'jotai',
      'mui',
      'data grid',
    ],
  },
  {
    id: 'product-engineering',
    weight: 2,
    aliases: [
      '제품',
      '프로덕트',
      '서비스',
      '문제 해결',
      '문제해결',
      '요구사항',
      '기획',
      '설계',
      '초기 설계',
      '구조',
      '구조화',
      '표준화',
      '리팩토링',
      '품질',
      'qa',
      '사용성',
      'ux',
      '디자인 시스템',
      '프론트엔드 구조',
      '유지보수성',
    ],
  },
  {
    id: 'delivery',
    weight: 2,
    aliases: [
      'ci/cd',
      'cicd',
      '배포',
      '테스트',
      'playwright',
      'docker',
      'github actions',
      '빌드',
      '검증',
      'typecheck',
      'pre-push',
      'husky',
      'runner',
      'e2e',
      '회귀',
      '브라우저 테스트',
      '자동 검증',
      '테스트 베드',
    ],
  },
  {
    id: 'product-data-flow',
    weight: 2,
    aliases: [
      '분석',
      '차트',
      '데이터',
      '조회',
      '저장',
      '업로드',
      '다운로드',
      '유효성',
      '유효성 검사',
      '캐시',
      '상태',
      '상태 관리',
      '폼',
      'api 연동',
      'api 연결',
      '서버 상태',
      '로딩',
      '에러',
      '타입 안정성',
      '타입 검사',
      '타입 모델링',
      '도메인 모델',
      '페이지네이션',
      '필터',
      'tanstack query',
      'zustand',
      'react hook form',
      'echarts',
      'plotly',
      'swr',
      'jotai',
    ],
  },
  {
    id: 'automation-ai',
    weight: 2,
    aliases: [
      '자동화',
      'ai',
      'llm',
      'codex',
      'bedrock',
      'openai',
      'translate',
      '번역',
      '자막',
      '프롬프트',
      '검수',
      '생산성',
      'pr 리뷰',
      '업무 자동화',
      '콘텐츠 운영',
      '콘텐츠 확인',
      '운영 도구',
      '관리 도구',
      '작업 생산성',
      '팀 리소스',
      '크롤링',
      '무단 도용',
      'vtt',
      'hls',
    ],
  },
  {
    id: 'commerce-operations',
    weight: 2,
    aliases: [
      '커머스',
      '백오피스',
      '운영자',
      'admin',
      '어드민',
      '관리자',
      '관리 화면',
      '관리 사이트',
      '주문',
      '상품',
      '셀러',
      '정산',
      '이벤트',
      '문의',
      '테이블',
      '다이얼로그',
      '드래그',
      '내보내기',
      '이커머스',
      '엑셀',
      'excel',
      'csv',
      'export',
      '매출',
      '배너',
      '테마',
    ],
  },
  {
    id: 'mobile-webview',
    weight: 2,
    aliases: [
      '모바일',
      '웹뷰',
      'webview',
      'playground',
      '딥링크',
      'deep link',
      'sdk',
      '앱 배포',
      '운세',
      '게임형',
      '콘텐츠',
      'safe area',
      'flutter bridge',
      'bridge',
      '앱 연동',
      '마케팅 연동',
      '랭킹',
      '결과 제출',
      '사운드',
      '배너',
    ],
  },
  {
    id: 'performance',
    weight: 2,
    aliases: [
      '성능',
      '최적화',
      'lcp',
      'speed index',
      'lighthouse',
      '렌더링',
      'webp',
      '이미지',
      'chrome',
      'safari',
      'webkit',
      '반응형',
      '호환성',
      'web vitals',
      'ttfb',
      'cache-control',
      'cache control',
      '응답 속도',
      '성능 튜닝',
    ],
  },
  {
    id: 'operations-infra',
    weight: 2,
    aliases: [
      '운영',
      '유지보수',
      '장애',
      '장애 대응',
      'api',
      '보안',
      '인프라',
      '마이그레이션',
      '데이터베이스',
      'windows',
      '매뉴얼',
      '모니터링',
      '사용자 영향',
      '수정 범위',
      '운영 안정성',
      '운영팀',
      '오류',
      '변경 요청',
      '콜센터',
    ],
  },
  {
    id: 'career-intent',
    weight: 2,
    aliases: [
      '이력',
      '경력',
      '커리어',
      '업무',
      '프로젝트',
      '경험',
      '강점',
      '성과',
      '기여',
      'resume',
      'career',
      'experience',
      'strength',
      'project',
    ],
  },
];

const OUT_OF_SCOPE_ANSWER_BY_LOCALE: Record<string, string> = {
  'ko-KR':
    '이 질문은 제 이력 범위를 벗어난 것 같아요. 프로젝트, 기술 경험, 업무 성과, 강점처럼 이력과 관련된 내용으로 다시 물어봐 주세요.',
  'en-US':
    'This question seems outside the scope of my resume. Please ask about resume-related topics such as projects, technical experience, work impact, or strengths.',
  'ja-JP':
    'この質問は私の履歴の範囲から外れているようです。プロジェクト、技術経験、業務成果、強みなど履歴に関連する内容で質問してください。',
};

const normalizeKeywordText = (value: string): string =>
  value
    .normalize('NFKC')
    .toLowerCase()
    .replace(/[._/+-]+/g, ' ')
    .replace(/[^\p{L}\p{N}#]+/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim();

export const calculateResumeRagKeywordScore = (question: string): number => {
  const normalizedQuestion = normalizeKeywordText(question);
  if (!normalizedQuestion) return 0;

  return RESUME_RAG_KEYWORD_GROUPS.reduce((score, group) => {
    const matched = group.aliases.some((alias) =>
      normalizedQuestion.includes(normalizeKeywordText(alias)),
    );

    return matched ? score + group.weight : score;
  }, 0);
};

export const isResumeRagQuestionInScope = (question: string): boolean =>
  calculateResumeRagKeywordScore(question) >= MIN_RESUME_RAG_KEYWORD_SCORE;

export const getResumeRagOutOfScopeAnswer = (locale: string): string =>
  OUT_OF_SCOPE_ANSWER_BY_LOCALE[locale] ??
  OUT_OF_SCOPE_ANSWER_BY_LOCALE['ko-KR'];
