/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 서버 상태 확인 */
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** API 헬스 체크 */
    get: operations["AppController_getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/espresso-history/beans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 에스프레소 원두 목록 조회 */
    get: operations["EspressoHistoryController_getBeans"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/espresso-history/beans/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 에스프레소 원두 상세 조회 */
    get: operations["EspressoHistoryController_getBeanById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 게임 결과 생성 및 랭킹 확인 */
    post: operations["GameController_createResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/ranking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 게임별 Top 10 랭킹 조회 */
    get: operations["GameController_getRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 게임 결과 상세 조회 */
    get: operations["GameController_getGameResult"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/main-chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 공개 프로젝트 상세와 사이트 안내 RAG 질문 답변 */
    post: operations["MainChatController_chat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 레시피 목록 조회 */
    get: operations["RecipeController_getRecipes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 레시피 상세 조회 */
    get: operations["RecipeController_getRecipeById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resume-rag/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이력 RAG 질문 답변 */
    post: operations["ResumeRagController_chat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resume-rag/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 익명 대화 생성. 30일 후 만료된다. */
    post: operations["ResumeConversationController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resume-rag/conversations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 저장 대화 최근 기록 조회 */
    get: operations["ResumeConversationController_history"];
    put?: never;
    post?: never;
    /** 저장 대화와 연결된 기록 삭제 */
    delete: operations["ResumeConversationController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wordle/word": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 랜덤 5글자 단어 조회 */
    get: operations["WordleController_getRandomWord"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wordle/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 단어 유효성 검사 */
    post: operations["WordleController_checkWord"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiErrorResponseDto: {
      /**
       * @description 오류 응답 여부
       * @example false
       * @enum {boolean}
       */
      success: false;
      /**
       * @description HTTP 오류 상태
       * @example 400
       */
      statusCode: number;
      /**
       * Format: date-time
       * @description 오류 응답 생성 시각
       * @example 2026-09-10T00:00:00.000Z
       */
      timestamp: string;
      /**
       * @description 요청 경로. query가 있으면 포함한다.
       * @example /wordle/check
       */
      path: string;
      /**
       * @description 오류 설명 또는 입력 검증 오류 목록
       * @example [
       *       "단어는 반드시 5글자여야 합니다."
       *     ]
       */
      message?: string | string[];
      /**
       * @description Nest HTTP 오류 이름
       * @example Bad Request
       */
      error?: string;
    };
    HealthCheckResponseDto: {
      /** @example ok */
      status: string;
      /**
       * @description API process uptime in seconds
       * @example 123.45
       */
      uptime: number;
      /**
       * @description Health check response time in ISO 8601 format
       * @example 2026-07-05T00:00:00.000Z
       */
      timestamp: string;
    };
    EspressoEquipmentDto: {
      /**
       * @description 에스프레소 머신
       * @example CRM 3605 PWM 2버전
       */
      machine?: string;
      /**
       * @description 그라인더
       * @example DF64 Gen2
       */
      grinder?: string;
      /**
       * @description 바스켓
       * @example IMS 20g
       */
      basket?: string;
      /**
       * @description 도징 쉐이커
       * @example 도징쉐이커
       */
      dosingShaker?: string;
      /**
       * @description 탬퍼
       * @example 58.5mm tamper
       */
      tamper?: string;
    };
    EspressoMeasurementDto: {
      /**
       * @description 단일 측정값
       * @example 20
       */
      value?: number;
      /**
       * @description 범위 최소값
       * @example 25
       */
      min?: number;
      /**
       * @description 범위 최대값
       * @example 30
       */
      max?: number;
      /**
       * @description 측정 단위
       * @example g
       * @enum {string}
       */
      unit: "g" | "sec" | "celsius" | "bar";
    };
    EspressoRecipeParametersDto: {
      dose?: components["schemas"]["EspressoMeasurementDto"];
      yield?: components["schemas"]["EspressoMeasurementDto"];
      temperature?: components["schemas"]["EspressoMeasurementDto"];
      preinfusion?: components["schemas"]["EspressoMeasurementDto"];
      extractionTime?: components["schemas"]["EspressoMeasurementDto"];
      targetExtractionTime?: components["schemas"]["EspressoMeasurementDto"];
      pressure?: components["schemas"]["EspressoMeasurementDto"];
      /**
       * @description 유량 조건
       * @example 기본 유량
       */
      flow?: string;
      /**
       * @description 분쇄도 조건
       * @example 2.4
       */
      grind?: string;
    };
    EspressoResultDto: {
      extractionTime?: components["schemas"]["EspressoMeasurementDto"];
      pressure?: components["schemas"]["EspressoMeasurementDto"];
      /** @description 맛 기록 */
      taste?: string[];
      /** @description 추가 메모 */
      notes?: string[];
    };
    EspressoRoundAnalysisDto: {
      /** @description 변경 사항 */
      changes?: string[];
      /** @description 기록 메모 */
      notes?: string[];
      /** @description 판단 */
      judgments?: string[];
      /** @description 추론 */
      inferences?: string[];
      /** @description 결론 */
      conclusions?: string[];
      /** @description 비교 예정 항목 */
      plannedComparisons?: string[];
    };
    EspressoRoundResponseDto: {
      /**
       * @description 라운드 ID
       * @example round-1
       */
      id: string;
      /**
       * @description 라운드 번호
       * @example 1
       */
      roundNumber: number;
      /**
       * @description 추출 일자
       * @example 2026-06-16
       */
      date?: string | null;
      /** @description 추출 레시피 */
      recipe: components["schemas"]["EspressoRecipeParametersDto"];
      /** @description 추출 결과 */
      result: components["schemas"]["EspressoResultDto"];
      /** @description 라운드 분석 */
      analysis?: components["schemas"]["EspressoRoundAnalysisDto"];
      /** @description 다음 액션 */
      nextActions: string[];
    };
    EspressoCurrentAnalysisDto: {
      /** @description 현재 조건 */
      conditions?: string[];
      /** @description 추정 문제 */
      suspectedIssues?: string[];
    };
    EspressoAdjustmentGuideDto: {
      /**
       * @description 조정 조건
       * @example 여전히 20초 이하
       */
      condition: string;
      /**
       * @description 조정 액션
       * @example 분쇄도 아주 조금만 가늘게
       */
      action: string;
    };
    EspressoMethodStepDto: {
      /**
       * @description 추출 시점
       * @example 0-5초
       */
      time: string;
      /** @description 수행 단계 */
      steps: string[];
    };
    EspressoNextTestDto: {
      /**
       * @description 목표 라운드 번호
       * @example 5
       */
      targetRoundNumber?: number;
      /** @description 다음 테스트 목표 */
      goals: string[];
      recipe: components["schemas"]["EspressoRecipeParametersDto"];
      method: components["schemas"]["EspressoMethodStepDto"][];
      /** @description 예상 결과 */
      expectedResult: string[];
    };
    EspressoLogResponseDto: {
      /**
       * @description 추출 로그 ID
       * @example fritz-jal-doeeo-gasina-log
       */
      id: string;
      /**
       * @description 로그 타입
       * @example espresso-log
       * @enum {string}
       */
      type: "espresso-log";
      /**
       * @description 추출 로그 제목
       * @example 추출 세팅
       */
      title: string;
      /** @description 라운드 기록 */
      rounds: components["schemas"]["EspressoRoundResponseDto"][];
      /** @description 현재 기준 분석 */
      currentAnalysis?: components["schemas"]["EspressoCurrentAnalysisDto"];
      /** @description 조건별 조정 가이드 */
      adjustmentGuide?: components["schemas"]["EspressoAdjustmentGuideDto"][];
      /** @description 최종 가설 */
      finalHypothesis?: string[];
      /** @description 다음 테스트 세팅 */
      nextTest?: components["schemas"]["EspressoNextTestDto"];
      /** @description 다음 방향 */
      nextDirection?: string[];
    };
    EspressoBeanResponseDto: {
      /**
       * @description 원두 기록 ID
       * @example bean-fritz-jal-doeeo-gasina
       */
      id: string;
      /**
       * @description 원두 이름
       * @example 프릳츠 잘 되어 가시나
       */
      name: string;
      /**
       * @description 로스터리
       * @example 프릳츠
       */
      roaster?: string;
      /** @description 원두 추출 목표 */
      goals: string[];
      /** @description 공통 장비 기본 세팅 */
      defaultEquipment: components["schemas"]["EspressoEquipmentDto"];
      /** @description 추출 로그 */
      logs: components["schemas"]["EspressoLogResponseDto"][];
    };
    /**
     * @description 서버에 등록된 게임 타입. 게임별 점수 정책은 서버에서 적용된다.
     * @enum {string}
     */
    GameType: "SKY_DROP";
    CreateGameHistoryDto: {
      /**
       * Format: int32
       * @description 게임별 서버 정책으로 최종 검증되는 정수 점수. DTO는 전체 게임 타입의 제출 envelope만 검증한다.
       * @example 8500
       */
      score: number;
      /**
       * Format: int32
       * @description 플레이 시간(초). 제출되면 게임별 서버 정책의 점수 대비 비정상 속도 검증에 사용된다.
       * @example 120
       */
      playTime?: number | null;
      /**
       * @description 서버에 등록된 게임 타입. 게임별 점수 정책은 서버에서 적용된다.
       * @example SKY_DROP
       */
      gameType: components["schemas"]["GameType"];
    };
    GameHistoryUserDto: {
      /**
       * @description 사용자 닉네임
       * @example 홍길동
       */
      displayName: string;
    };
    GameHistoryResponseDto: {
      /**
       * @description 게임 기록 ID (UUID)
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 게임 타입
       * @example SKY_DROP
       * @enum {string}
       */
      gameType: "SKY_DROP";
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
      /**
       * @description 이번 판보다 높은 사용자별 최고점 개수 + 1. 본인의 과거 최고점도 비교하며 Top 10 밖도 숫자. 공개 결과 조회에서는 생략
       * @example 1
       */
      rank?: number;
      /**
       * @description 유저의 역대 최고 점수
       * @example 1200
       */
      bestScore?: number;
      /**
       * @description 전체 기간 랭킹
       * @example 42
       */
      allTimeRank?: number;
      /**
       * @description 금주 랭킹 (KST 월요일 0시 ~ 일요일 24시 기준)
       * @example 5
       */
      weeklyRank?: number;
    };
    GameRankingHistoryDto: {
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 순위
       * @example 1
       */
      rank: number;
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 공개 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
    };
    ResumeRagChatRequestDto: {
      /**
       * Format: uuid
       * @description 생성한 대화 ID. 접근키 헤더와 함께 전달한다.
       */
      conversationId?: string;
      /**
       * Format: uuid
       * @description 대화 요청 시 필수. 재시도에는 같은 UUID를 사용한다.
       */
      requestId?: string;
      /** @example 어떤 의료 도메인 프로젝트 경험이 있나요? */
      question: string;
      /**
       * @example ko-KR
       * @enum {string}
       */
      locale: "ko-KR" | "en-US" | "ja-JP";
    };
    ResumeRagSourceDto: {
      title: string;
      sourcePath: string;
      sourceKey: string;
      sectionPath?: string;
      version?: string;
      caveats?: string[];
      excerpt: string;
      similarity: number;
    };
    ResumeRagChatResponseDto: {
      /** Format: uuid */
      conversationId?: string;
      /** Format: uuid */
      requestId?: string;
      answer: string;
      grounded: boolean;
      sources: components["schemas"]["ResumeRagSourceDto"][];
    };
    RecipeSourceDto: {
      /**
       * @description 레시피 출처 유형
       * @example notion
       */
      type: string;
      /**
       * @description 레시피 원문 URL
       * @example https://www.notion.so/example
       */
      url: string;
    };
    RecipeResponseDto: {
      /**
       * Format: uuid
       * @description 레시피 ID
       * @example 411b3333-a8b1-414b-bd60-9f538a885614
       */
      id: string;
      /**
       * @description 레시피 이름
       * @example 부타동
       */
      name: string;
      /** @description 검색 및 분류 태그 */
      tags: string[];
      /** @description 재료 목록 */
      ingredients: string[];
      /** @description 조리 단계 */
      recipe: string[];
      /** @description 레시피 출처 */
      source?: components["schemas"]["RecipeSourceDto"];
      /**
       * Format: date-time
       * @description 생성 시각
       * @example 2026-06-16T12:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 수정 시각
       * @example 2026-06-16T12:00:00.000Z
       */
      updatedAt: string;
    };
    CreateResumeConversationDto: {
      /** @enum {string} */
      locale: "ko-KR" | "en-US" | "ja-JP";
      /** @enum {string} */
      channel: "main" | "resume";
    };
    ResumeConversationAccessDto: {
      /** Format: uuid */
      id: string;
      /** @description 대화 생성 시 한 번 반환하는 접근키. URL이나 로그에 기록하지 않는다. */
      token: string;
      /** Format: date-time */
      expiresAt: string;
    };
    ResumeConversationTurnDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      requestId: string;
      question: string;
      answer: string;
      grounded: boolean;
      sources: components["schemas"]["ResumeRagSourceDto"][];
      /** Format: date-time */
      createdAt: string;
    };
    ResumeConversationHistoryDto: {
      /** @enum {string} */
      locale: "ko-KR" | "en-US" | "ja-JP";
      /** @enum {string} */
      channel: "main" | "resume";
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      expiresAt: string;
      /** @description 최근 50개 질문·답변 쌍 */
      turns: components["schemas"]["ResumeConversationTurnDto"][];
    };
    WordResponseDto: {
      /**
       * @description 5글자 영단어
       * @example apple
       */
      word: string;
    };
    CheckWordDto: {
      /**
       * @description 확인할 5글자 영단어
       * @example apple
       */
      word: string;
    };
    CheckWordResponseDto: {
      /**
       * @description 단어 존재 여부
       * @example true
       */
      exists: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 서버가 정상적으로 동작 중임을 나타내는 메시지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            /** @example Hello World! */
            data: string;
          };
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  AppController_getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API 프로세스가 정상적으로 요청을 처리할 수 있는 상태 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["HealthCheckResponseDto"];
          };
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  EspressoHistoryController_getBeans: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 에스프레소 원두 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["EspressoBeanResponseDto"][];
          };
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  EspressoHistoryController_getBeanById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 원두 기록 ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 에스프레소 원두 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["EspressoBeanResponseDto"];
          };
        };
      };
      /** @description 해당 원두 기록이 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  GameController_createResult: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameHistoryDto"];
      };
    };
    responses: {
      /** @description 게임 결과 저장 및 이번 판·전체·주간 등수 반환 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["GameHistoryResponseDto"];
          };
        };
      };
      /** @description 지원하지 않는 게임 타입 또는 점수·플레이 시간 정책 위반 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description Google ID token이 없거나 유효하지 않음 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  GameController_getRanking: {
    parameters: {
      query: {
        /** @description 조회할 게임 타입 */
        gameType: components["schemas"]["GameType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 사용자별 최고 점수 기준 상위 10건 조회 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["GameRankingHistoryDto"][];
          };
        };
      };
      /** @description 조회할 gameType이 없거나 지원하지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  GameController_getGameResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공유된 게임 결과 조회 (로그인 필요 없음) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["GameHistoryResponseDto"];
          };
        };
      };
      /** @description 결과 ID가 UUID가 아님 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 해당 게임 결과가 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  MainChatController_chat: {
    parameters: {
      query?: never;
      header?: {
        "X-Resume-Conversation-Token"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeRagChatRequestDto"];
      };
    };
    responses: {
      /** @description 공개 프로젝트·사이트 안내 답변 반환. 저장 대화는 식별자를 포함한다. */
      200: {
        headers: {
          /** @description IP당 1시간 메인 채팅 요청 최대 횟수 */
          "X-RateLimit-Limit"?: number;
          /** @description 현재 IP에서 남은 메인 채팅 요청 횟수 */
          "X-RateLimit-Remaining"?: number;
          /** @description 다음 메인 채팅 요청 횟수가 복구되는 Unix epoch 초 */
          "X-RateLimit-Reset"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["ResumeRagChatResponseDto"];
          };
        };
      };
      /** @description 질문 길이 또는 locale 형식이 올바르지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 허용된 VSCoke 웹 origin이 아닌 요청 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 접근키, 채널 또는 언어 불일치나 삭제·만료된 대화 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 다른 질문에 사용된 요청 ID 또는 동시 대화 버전 충돌 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description IP당 1시간에 허용된 메인 채팅 요청 횟수를 초과함 */
      429: {
        headers: {
          /** @description IP당 1시간 메인 채팅 요청 최대 횟수 */
          "X-RateLimit-Limit"?: number;
          /** @description 현재 IP에서 남은 메인 채팅 요청 횟수 */
          "X-RateLimit-Remaining"?: number;
          /** @description 다음 메인 채팅 요청 횟수가 복구되는 Unix epoch 초 */
          "X-RateLimit-Reset"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 검색 또는 답변 생성 공급자를 사용할 수 없음 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  RecipeController_getRecipes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 레시피 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["RecipeResponseDto"][];
          };
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  RecipeController_getRecipeById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 레시피 UUID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 레시피 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["RecipeResponseDto"];
          };
        };
      };
      /** @description 레시피 ID가 UUID 형식이 아님 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 해당 레시피가 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  ResumeRagController_chat: {
    parameters: {
      query?: never;
      header?: {
        "X-Resume-Conversation-Token"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeRagChatRequestDto"];
      };
    };
    responses: {
      /** @description 공개 이력 근거 답변 반환. 저장 대화는 식별자를 포함한다. */
      200: {
        headers: {
          /** @description IP당 1시간 이력 채팅 요청 최대 횟수 */
          "X-RateLimit-Limit"?: number;
          /** @description 현재 IP에서 남은 이력 채팅 요청 횟수 */
          "X-RateLimit-Remaining"?: number;
          /** @description 다음 이력 채팅 요청 횟수가 복구되는 Unix epoch 초 */
          "X-RateLimit-Reset"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["ResumeRagChatResponseDto"];
          };
        };
      };
      /** @description 질문·언어·대화 요청 식별자가 올바르지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 허용된 VSCoke 웹 origin이 아닌 요청 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 접근키, 채널 또는 언어 불일치나 삭제·만료된 대화 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 다른 질문에 사용된 요청 ID 또는 동시 대화 버전 충돌 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description IP당 1시간에 허용된 이력 채팅 요청 횟수를 초과함 */
      429: {
        headers: {
          /** @description IP당 1시간 이력 채팅 요청 최대 횟수 */
          "X-RateLimit-Limit"?: number;
          /** @description 현재 IP에서 남은 이력 채팅 요청 횟수 */
          "X-RateLimit-Remaining"?: number;
          /** @description 다음 이력 채팅 요청 횟수가 복구되는 Unix epoch 초 */
          "X-RateLimit-Reset"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 검색 또는 답변 생성 공급자를 사용할 수 없음 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  ResumeConversationController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateResumeConversationDto"];
      };
    };
    responses: {
      /** @description 대화 생성 성공. 비밀 접근키는 이 응답에서만 제공한다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["ResumeConversationAccessDto"];
          };
        };
      };
      /** @description 대화 ID, 채널 또는 언어 형식이 올바르지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 허용되지 않은 웹 origin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description IP당 1시간 대화 관리 요청 120회 초과 */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  ResumeConversationController_history: {
    parameters: {
      query?: never;
      header: {
        "X-Resume-Conversation-Token": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 접근키로 검증한 대화의 최근 50턴 조회 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["ResumeConversationHistoryDto"];
          };
        };
      };
      /** @description 대화 ID, 채널 또는 언어 형식이 올바르지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 허용되지 않은 웹 origin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 접근키 불일치, 삭제 또는 만료된 대화 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description IP당 1시간 대화 관리 요청 120회 초과 */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  ResumeConversationController_remove: {
    parameters: {
      query?: never;
      header: {
        "X-Resume-Conversation-Token": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 대화와 연결된 턴 삭제 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: {
              deleted: boolean;
            };
          };
        };
      };
      /** @description 대화 ID, 채널 또는 언어 형식이 올바르지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 허용되지 않은 웹 origin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 접근키 불일치, 삭제 또는 만료된 대화 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description IP당 1시간 대화 관리 요청 120회 초과 */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  WordleController_getRandomWord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 랜덤으로 선택된 5글자 영단어 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["WordResponseDto"];
          };
        };
      };
      /** @description 준비된 단어가 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  WordleController_checkWord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckWordDto"];
      };
    };
    responses: {
      /** @description 단어 존재 여부 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CheckWordResponseDto"];
          };
        };
      };
      /** @description 입력 단어가 5글자 영문이 아니거나 허용되지 않은 필드가 있음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
      /** @description 분류되지 않은 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
}
