/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 서버 상태 확인 */
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** API 헬스 체크 */
    get: operations["AppController_getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/espresso-history/beans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 에스프레소 원두 목록 조회 */
    get: operations["EspressoHistoryController_getBeans"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/espresso-history/beans/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 에스프레소 원두 상세 조회 */
    get: operations["EspressoHistoryController_getBeanById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 게임 결과 생성 및 랭킹 확인 */
    post: operations["GameController_createResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/poke-lounge/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poke Lounge 상태 조회 */
    get: operations["GameController_getPokeLoungeState"];
    /** Poke Lounge 상태 저장 */
    put: operations["GameController_savePokeLoungeState"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/ranking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게임별 Top 10 랭킹 조회
     * @description POKE_LOUNGE는 서버에서 검증된 대전 결과만 포함합니다. 응답은 항상 랭킹 배열입니다.
     */
    get: operations["GameController_getRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 게임 결과 상세 조회 */
    get: operations["GameController_getGameResult"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_createRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PokeLoungeController_getRoom"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/competitive-seat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_bindCompetitiveSeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/matches/{matchId}/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_submitCompetitiveAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_joinRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_setReady"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/party-snapshot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_updatePartySnapshot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a casual Poke Lounge result
     * @description Client-reported room results remain unverified and cannot create verified trust or public ranking entries.
     */
    post: operations["PokeLoungeController_submitResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_leaveRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 레시피 목록 조회 */
    get: operations["RecipeController_getRecipes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 레시피 상세 조회 */
    get: operations["RecipeController_getRecipeById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/resume-rag/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이력 RAG 질문 답변 */
    post: operations["ResumeRagController_chat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wordle/word": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 랜덤 5글자 단어 조회 */
    get: operations["WordleController_getRandomWord"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wordle/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 단어 유효성 검사 */
    post: operations["WordleController_checkWord"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthCheckResponseDto: {
      /** @example ok */
      status: string;
      /**
       * @description API process uptime in seconds
       * @example 123.45
       */
      uptime: number;
      /**
       * @description Health check response time in ISO 8601 format
       * @example 2026-07-05T00:00:00.000Z
       */
      timestamp: string;
    };
    EspressoEquipmentDto: {
      /**
       * @description 에스프레소 머신
       * @example CRM 3605 PWM 2버전
       */
      machine?: string;
      /**
       * @description 그라인더
       * @example DF64 Gen2
       */
      grinder?: string;
      /**
       * @description 바스켓
       * @example IMS 20g
       */
      basket?: string;
      /**
       * @description 도징 쉐이커
       * @example 도징쉐이커
       */
      dosingShaker?: string;
      /**
       * @description 탬퍼
       * @example 58.5mm tamper
       */
      tamper?: string;
    };
    EspressoMeasurementDto: {
      /**
       * @description 단일 측정값
       * @example 20
       */
      value?: number;
      /**
       * @description 범위 최소값
       * @example 25
       */
      min?: number;
      /**
       * @description 범위 최대값
       * @example 30
       */
      max?: number;
      /**
       * @description 측정 단위
       * @example g
       * @enum {string}
       */
      unit: "g" | "sec" | "celsius" | "bar";
    };
    EspressoRecipeParametersDto: {
      dose?: components["schemas"]["EspressoMeasurementDto"];
      yield?: components["schemas"]["EspressoMeasurementDto"];
      temperature?: components["schemas"]["EspressoMeasurementDto"];
      preinfusion?: components["schemas"]["EspressoMeasurementDto"];
      extractionTime?: components["schemas"]["EspressoMeasurementDto"];
      targetExtractionTime?: components["schemas"]["EspressoMeasurementDto"];
      pressure?: components["schemas"]["EspressoMeasurementDto"];
      /**
       * @description 유량 조건
       * @example 기본 유량
       */
      flow?: string;
      /**
       * @description 분쇄도 조건
       * @example 2.4
       */
      grind?: string;
    };
    EspressoResultDto: {
      extractionTime?: components["schemas"]["EspressoMeasurementDto"];
      pressure?: components["schemas"]["EspressoMeasurementDto"];
      /** @description 맛 기록 */
      taste?: string[];
      /** @description 추가 메모 */
      notes?: string[];
    };
    EspressoRoundAnalysisDto: {
      /** @description 변경 사항 */
      changes?: string[];
      /** @description 기록 메모 */
      notes?: string[];
      /** @description 판단 */
      judgments?: string[];
      /** @description 추론 */
      inferences?: string[];
      /** @description 결론 */
      conclusions?: string[];
      /** @description 비교 예정 항목 */
      plannedComparisons?: string[];
    };
    EspressoRoundResponseDto: {
      /**
       * @description 라운드 ID
       * @example round-1
       */
      id: string;
      /**
       * @description 라운드 번호
       * @example 1
       */
      roundNumber: number;
      /**
       * @description 추출 일자
       * @example 2026-06-16
       */
      date?: string | null;
      /** @description 추출 레시피 */
      recipe: components["schemas"]["EspressoRecipeParametersDto"];
      /** @description 추출 결과 */
      result: components["schemas"]["EspressoResultDto"];
      /** @description 라운드 분석 */
      analysis?: components["schemas"]["EspressoRoundAnalysisDto"];
      /** @description 다음 액션 */
      nextActions: string[];
    };
    EspressoCurrentAnalysisDto: {
      /** @description 현재 조건 */
      conditions?: string[];
      /** @description 추정 문제 */
      suspectedIssues?: string[];
    };
    EspressoAdjustmentGuideDto: {
      /**
       * @description 조정 조건
       * @example 여전히 20초 이하
       */
      condition: string;
      /**
       * @description 조정 액션
       * @example 분쇄도 아주 조금만 가늘게
       */
      action: string;
    };
    EspressoMethodStepDto: {
      /**
       * @description 추출 시점
       * @example 0-5초
       */
      time: string;
      /** @description 수행 단계 */
      steps: string[];
    };
    EspressoNextTestDto: {
      /**
       * @description 목표 라운드 번호
       * @example 5
       */
      targetRoundNumber?: number;
      /** @description 다음 테스트 목표 */
      goals: string[];
      recipe: components["schemas"]["EspressoRecipeParametersDto"];
      method: components["schemas"]["EspressoMethodStepDto"][];
      /** @description 예상 결과 */
      expectedResult: string[];
    };
    EspressoLogResponseDto: {
      /**
       * @description 추출 로그 ID
       * @example fritz-jal-doeeo-gasina-log
       */
      id: string;
      /**
       * @description 로그 타입
       * @example espresso-log
       * @enum {string}
       */
      type: "espresso-log";
      /**
       * @description 추출 로그 제목
       * @example 추출 세팅
       */
      title: string;
      /** @description 라운드 기록 */
      rounds: components["schemas"]["EspressoRoundResponseDto"][];
      /** @description 현재 기준 분석 */
      currentAnalysis?: components["schemas"]["EspressoCurrentAnalysisDto"];
      /** @description 조건별 조정 가이드 */
      adjustmentGuide?: components["schemas"]["EspressoAdjustmentGuideDto"][];
      /** @description 최종 가설 */
      finalHypothesis?: string[];
      /** @description 다음 테스트 세팅 */
      nextTest?: components["schemas"]["EspressoNextTestDto"];
      /** @description 다음 방향 */
      nextDirection?: string[];
    };
    EspressoBeanResponseDto: {
      /**
       * @description 원두 기록 ID
       * @example bean-fritz-jal-doeeo-gasina
       */
      id: string;
      /**
       * @description 원두 이름
       * @example 프릳츠 잘 되어 가시나
       */
      name: string;
      /**
       * @description 로스터리
       * @example 프릳츠
       */
      roaster?: string;
      /** @description 원두 추출 목표 */
      goals: string[];
      /** @description 공통 장비 기본 세팅 */
      defaultEquipment: components["schemas"]["EspressoEquipmentDto"];
      /** @description 추출 로그 */
      logs: components["schemas"]["EspressoLogResponseDto"][];
    };
    /**
     * @description 서버에 등록된 게임 타입. 게임별 점수 정책은 서버에서 적용된다.
     * @enum {string}
     */
    GameType: "SKY_DROP" | "POKE_LOUNGE";
    CreateGameHistoryDto: {
      /**
       * @description 게임별 서버 정책으로 최종 검증되는 정수 점수. DTO는 전체 게임 타입의 제출 envelope만 검증한다.
       * @example 8500
       */
      score: number;
      /**
       * @description 플레이 시간(초). 제출되면 게임별 서버 정책의 점수 대비 비정상 속도 검증에 사용된다.
       * @example 120
       */
      playTime?: number;
      /**
       * @description 서버에 등록된 게임 타입. 게임별 점수 정책은 서버에서 적용된다.
       * @example SKY_DROP
       */
      gameType: components["schemas"]["GameType"];
    };
    GameHistoryUserDto: {
      /**
       * @description 사용자 닉네임
       * @example 홍길동
       */
      displayName: string;
    };
    GameHistoryResponseDto: {
      /**
       * @description 게임 기록 ID (UUID)
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 게임 타입
       * @example SKY_DROP
       * @enum {string}
       */
      gameType: "SKY_DROP" | "POKE_LOUNGE";
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
      /**
       * @description 현재 등수 (1부터 시작, 랭킹 외 시 null)
       * @example 1
       */
      rank?: number | null;
      /**
       * @description 유저의 역대 최고 점수
       * @example 1200
       */
      bestScore?: number | null;
      /**
       * @description 전체 기간 랭킹
       * @example 42
       */
      allTimeRank?: number | null;
      /**
       * @description 금주 랭킹 (KST 월요일 0시 ~ 일요일 24시 기준)
       * @example 5
       */
      weeklyRank?: number | null;
    };
    SavePokeLoungeStateDto: {
      /**
       * @description Poke Lounge 클라이언트의 현재 저장 상태
       * @example {
       *       "trainer": {
       *         "x": 12,
       *         "y": 3
       *       },
       *       "party": [
       *         "pikachu",
       *         "eevee"
       *       ]
       *     }
       */
      state: {
        [key: string]: unknown;
      };
      /**
       * @description 클라이언트 기준 상태 갱신 시각
       * @example 2026-07-08T12:00:00.000Z
       */
      clientUpdatedAt?: string;
    };
    PokeLoungeStateResponseDto: {
      /**
       * @description Poke Lounge 상태 저장 ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 상태를 저장한 사용자 ID
       * @example google-sub-id
       */
      userId: string;
      /** @description Poke Lounge 클라이언트의 저장 상태 */
      state: {
        [key: string]: unknown;
      };
      /**
       * Format: date-time
       * @description 서버 저장 생성 시각
       * @example 2026-07-08T12:00:01.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 서버 저장 갱신 시각
       * @example 2026-07-08T12:00:02.000Z
       */
      updatedAt: string;
      /**
       * @description 클라이언트 기준 상태 갱신 시각
       * @example 2026-07-08T12:00:00.000Z
       */
      clientUpdatedAt?: Record<string, never> | null;
    };
    GameRankingHistoryDto: {
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 순위
       * @example 1
       */
      rank: number;
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 공개 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
    };
    CreatePokeLoungeRoomDto: {
      /** @example player-a */
      playerId?: string;
      /** @example session-a */
      sessionId: string;
      /** @example user-123 */
      userId?: string;
      /** @example Player A */
      displayName?: string;
      /** @example 60000 */
      roundDurationMs?: number;
      /** @example 1720000000000 */
      nowMs?: number;
    };
    PokeLoungeRepresentativePokemonDto: {
      /** @example 25 */
      speciesId: number;
      /** @example Pikachu */
      name: string;
      /** @example 12 */
      level: number;
      /** @example 18 */
      currentHp: number;
      /** @example 30 */
      maxHp: number;
    };
    PokeLoungePartySnapshotDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName?: string;
      representativePokemon?: components["schemas"]["PokeLoungeRepresentativePokemonDto"];
      /** @example 1720000002000 */
      updatedAtMs: number;
    };
    CompetitiveMoveStateDto: {
      moveId: string;
      pp: number;
    };
    CompetitiveCombatantStateDto: {
      speciesId: string;
      maxHp: number;
      currentHp: number;
      /** @enum {string} */
      status: "none" | "paralyzed";
      moves: components["schemas"]["CompetitiveMoveStateDto"][];
    };
    CompetitivePlayerStateDto: {
      playerId: string;
      activeSlotIndex: number;
      team: components["schemas"]["CompetitiveCombatantStateDto"][];
    };
    CompetitiveTerminalResultDto: {
      winnerPlayerId: string;
      loserPlayerId: string;
      /** @enum {string} */
      reason: "faint" | "forfeit" | "timeout";
      scoreByPlayerId: {
        [key: string]: 50 | 100;
      };
    };
    CompetitiveBattleStateDto: {
      /** @example 1 */
      rulesetVersion: number;
      turn: number;
      participantIds: string[];
      playersById: {
        [key: string]: components["schemas"]["CompetitivePlayerStateDto"];
      };
      terminal: components["schemas"]["CompetitiveTerminalResultDto"] | null;
    };
    CompetitiveActionResponseDto: {
      matchId: string;
      /** @example game-round-1-bracket-1-match-1 */
      bracketMatchId: string;
      /** @enum {string} */
      kind: "ranked-head-to-head" | "tournament-unranked";
      assignmentRevision: number;
      rulesetVersion: number;
      rulesetHash: string;
      currentTurn: number;
      /** @enum {string} */
      status: "pending" | "active" | "completed";
      /** Format: uuid */
      terminalEventId: string | null;
      terminalRoomRevision: number | null;
      playerIds: string[];
      stateHash: string;
      currentState: components["schemas"]["CompetitiveBattleStateDto"];
      submittedPlayerIds: string[];
      terminal: components["schemas"]["CompetitiveTerminalResultDto"] | null;
    };
    CompetitiveTerminalTransitionDto: {
      /** Format: uuid */
      terminalEventId: string;
      terminalRoomRevision: number;
      projection: components["schemas"]["CompetitiveActionResponseDto"];
    };
    PokeLoungeRoomParticipantDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName: string;
      /**
       * @example participant
       * @enum {string}
       */
      role: "participant" | "spectator";
      /** @example true */
      ready: boolean;
      /** @example true */
      connected: boolean;
      /** @example 1720000000000 */
      joinedAtMs: number;
      /** @example 1720000005000 */
      leftAtMs?: number;
    };
    PokeLoungeRoundDto: {
      /** @example 1 */
      index: number;
      /**
       * @example waiting
       * @enum {string}
       */
      phase: "waiting" | "round-started" | "tournament" | "completed";
      /** @example 60000 */
      durationMs: number;
      /** @example 1720000000000 */
      startedAtMs: number | null;
      /** @example 1720000060000 */
      endsAtMs: number | null;
    };
    PokeLoungeTournamentParticipantDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName: string;
      /** @example 1 */
      seed: number;
    };
    PokeLoungeTournamentMatchDto: {
      /** @example game-round-1-bracket-1-match-1 */
      matchId: string;
      /** @example 1 */
      roundNumber: number;
      /** @example 1 */
      matchNumber: number;
      participantA: components["schemas"]["PokeLoungeTournamentParticipantDto"];
      participantB: components["schemas"]["PokeLoungeTournamentParticipantDto"];
      /**
       * @example [
       *       "player-a",
       *       "player-b"
       *     ]
       */
      participantIds: string[];
      /**
       * @example ready
       * @enum {string}
       */
      status: "ready" | "completed";
      /** @example player-a */
      winnerPlayerId: string | null;
      /** @example player-b */
      loserPlayerId: string | null;
      /**
       * @example faint
       * @enum {string|null}
       */
      resultReason: "faint" | "timeout" | "forfeit" | "run" | "capture" | null;
      /** @example 1720000060000 */
      completedAtMs: number | null;
    };
    PokeLoungeTournamentByeDto: {
      /** @example game-round-1-bracket-1-bye-1 */
      byeId: string;
      /** @example 1 */
      roundNumber: number;
      /** @example 1 */
      slotNumber: number;
      entrant: components["schemas"]["PokeLoungeTournamentParticipantDto"];
    };
    PokeLoungeTournamentRoundSlotDto: {
      /** @enum {string} */
      kind: "match" | "bye";
      /** @example game-round-1-bracket-1-match-1 */
      matchId?: string;
      /** @example game-round-1-bracket-1-bye-1 */
      byeId?: string;
    };
    PokeLoungeTournamentRoundDto: {
      /** @example 1 */
      roundNumber: number;
      matches: components["schemas"]["PokeLoungeTournamentMatchDto"][];
      byes: components["schemas"]["PokeLoungeTournamentByeDto"][];
      slots: components["schemas"]["PokeLoungeTournamentRoundSlotDto"][];
    };
    PokeLoungeTournamentEliminationDto: {
      /** @example player-b */
      playerId: string;
      /** @example Player B */
      displayName: string;
      /** @example 2 */
      seed: number;
      /** @example 1 */
      roundNumber: number;
      /** @example game-round-1-bracket-1-match-1 */
      matchId: string;
      /** @example 1 */
      order: number;
    };
    PokeLoungeTournamentBracketDto: {
      /**
       * @example 1
       * @enum {number}
       */
      version: 1;
      /** @example 1 */
      gameRoundIndex: number;
      /** @enum {string} */
      status: "in-progress" | "completed";
      participants: components["schemas"]["PokeLoungeTournamentParticipantDto"][];
      currentRound: components["schemas"]["PokeLoungeTournamentRoundDto"] | null;
      completedRounds: components["schemas"]["PokeLoungeTournamentRoundDto"][];
      eliminations: components["schemas"]["PokeLoungeTournamentEliminationDto"][];
      /** @example player-a */
      championPlayerId: string | null;
    };
    PokeLoungeTournamentDto: {
      /**
       * @example 2
       * @enum {number}
       */
      version: 2;
      bracket: components["schemas"]["PokeLoungeTournamentBracketDto"] | null;
      /** @example game-round-1-bracket-1-match-1 */
      activeMatchId: string | null;
      /** @enum {string|null} */
      activeMatchAuthority: "casual" | "server" | null;
      /**
       * @example {
       *       "player-a": 100,
       *       "player-b": 50
       *     }
       */
      cumulativeScores: {
        [key: string]: number;
      };
    };
    PokeLoungeFinalStandingDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName: string;
      /** @example 1 */
      rank: number;
      /** @example 100 */
      score: number;
    };
    PokeLoungeRoomResponseDto: {
      /** @example ROOM01 */
      roomCode: string;
      /**
       * @example waiting
       * @enum {string}
       */
      status: "waiting" | "round-started" | "tournament" | "completed" | "closed";
      /**
       * @example legacy-room-restart-required
       * @enum {string}
       */
      closeReason?: "legacy-room-restart-required";
      /** @example 1720000000000 */
      createdAtMs: number;
      /** @example 1720000001000 */
      updatedAtMs: number;
      /** @example 3 */
      revision: number;
      /** @example 1720001800000 */
      expiresAtMs: number;
      participants: components["schemas"]["PokeLoungeRoomParticipantDto"][];
      partySnapshots: {
        [key: string]: components["schemas"]["PokeLoungePartySnapshotDto"];
      };
      round: components["schemas"]["PokeLoungeRoundDto"];
      tournament: components["schemas"]["PokeLoungeTournamentDto"];
      finalStandings: components["schemas"]["PokeLoungeFinalStandingDto"][];
      competitiveTransitions: components["schemas"]["CompetitiveTerminalTransitionDto"][];
      competitive?: components["schemas"]["CompetitiveActionResponseDto"];
    };
    PokeLoungeRoomConflictResponseDto: {
      /** @example 409 */
      statusCode: number;
      /** @enum {string} */
      code: "POKE_LOUNGE_REVISION_CONFLICT" | "POKE_LOUNGE_IDEMPOTENCY_CONFLICT";
      /** @example Poke Lounge room revision conflict */
      message: string;
      snapshot: components["schemas"]["PokeLoungeRoomResponseDto"];
    };
    BindCompetitiveSeatDto: {
      /** @example session-a */
      sessionId: string;
    };
    CompetitiveAssignmentResponseDto: {
      matchId: string;
      /** @example game-round-1-bracket-1-match-1 */
      bracketMatchId: string;
      /** @enum {string} */
      kind: "ranked-head-to-head" | "tournament-unranked";
      assignmentRevision: number;
      rulesetVersion: number;
      rulesetHash: string;
      currentTurn: number;
      /** @enum {string} */
      status: "pending" | "active" | "completed";
      /** Format: uuid */
      terminalEventId: string | null;
      terminalRoomRevision: number | null;
      playerIds: string[];
      stateHash: string;
      currentState: components["schemas"]["CompetitiveBattleStateDto"];
      submittedPlayerIds: string[];
      terminal: components["schemas"]["CompetitiveTerminalResultDto"] | null;
    };
    CompetitiveActionDto: {
      /** @enum {string} */
      kind: "move" | "switch";
      /** @example steady-strike */
      moveId?: string;
      slotIndex?: number;
    };
    SubmitCompetitiveActionDto: {
      assignmentRevision: number;
      turn: number;
      /** Format: uuid */
      clientCommandId: string;
      action: components["schemas"]["CompetitiveActionDto"];
    };
    JoinPokeLoungeRoomDto: {
      /** @example player-b */
      playerId?: string;
      /** @example session-b */
      sessionId: string;
      /** @example user-456 */
      userId?: string;
      /** @example Player B */
      displayName?: string;
      /** @example 1720000001000 */
      nowMs?: number;
    };
    SetPokeLoungeReadyDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
      /** @example true */
      ready: boolean;
      /** @example 1720000002000 */
      nowMs?: number;
    };
    UpdatePokeLoungePartySnapshotDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
      /** @example Player A */
      displayName?: string;
      representativePokemon?: components["schemas"]["PokeLoungeRepresentativePokemonDto"];
      /** @example 1720000002000 */
      nowMs?: number;
    };
    SubmitPokeLoungeMatchResultDto: {
      /** @example player-a */
      reportingPlayerId: string;
      /** @example session-a */
      reportingSessionId: string;
      /** @example game-round-1-bracket-1-match-1 */
      matchId: string;
      /** @example player-a */
      winnerPlayerId: string;
      /** @example player-b */
      loserPlayerId: string;
      /**
       * @example faint
       * @enum {string}
       */
      reason: "faint" | "timeout" | "forfeit" | "run" | "capture";
      /** @example 1720000003000 */
      nowMs?: number;
    };
    LeavePokeLoungeRoomDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
      /** @example 1720000004000 */
      nowMs?: number;
    };
    RecipeSourceDto: {
      /**
       * @description 레시피 출처 유형
       * @example notion
       */
      type: string;
      /**
       * @description 레시피 원문 URL
       * @example https://www.notion.so/example
       */
      url: string;
    };
    RecipeResponseDto: {
      /**
       * Format: uuid
       * @description 레시피 ID
       * @example 411b3333-a8b1-414b-bd60-9f538a885614
       */
      id: string;
      /**
       * @description 레시피 이름
       * @example 부타동
       */
      name: string;
      /** @description 검색 및 분류 태그 */
      tags: string[];
      /** @description 재료 목록 */
      ingredients: string[];
      /** @description 조리 단계 */
      recipe: string[];
      /** @description 레시피 출처 */
      source?: components["schemas"]["RecipeSourceDto"];
      /**
       * Format: date-time
       * @description 생성 시각
       * @example 2026-06-16T12:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 수정 시각
       * @example 2026-06-16T12:00:00.000Z
       */
      updatedAt: string;
    };
    ResumeRagChatRequestDto: {
      /** @example 어떤 의료 도메인 프로젝트 경험이 있나요? */
      question: string;
      /**
       * @example ko-KR
       * @enum {string}
       */
      locale: "ko-KR" | "en-US" | "ja-JP";
    };
    ResumeRagSourceDto: {
      title: string;
      sourcePath: string;
      sourceKey: string;
      sectionPath?: string;
      version?: string;
      caveats?: string[];
      excerpt: string;
      similarity: number;
    };
    ResumeRagChatResponseDto: {
      answer: string;
      grounded: boolean;
      sources: components["schemas"]["ResumeRagSourceDto"][];
    };
    WordResponseDto: {
      /**
       * @description 5글자 영단어
       * @example apple
       */
      word: string;
    };
    CheckWordDto: {
      /**
       * @description 확인할 5글자 영단어
       * @example apple
       */
      word: string;
    };
    CheckWordResponseDto: {
      /**
       * @description 단어 존재 여부
       * @example true
       */
      exists: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 서버가 정상적으로 동작 중임을 나타내는 메시지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  AppController_getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API 프로세스가 정상적으로 요청을 처리할 수 있는 상태 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthCheckResponseDto"];
        };
      };
    };
  };
  EspressoHistoryController_getBeans: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 에스프레소 원두 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EspressoBeanResponseDto"][];
        };
      };
    };
  };
  EspressoHistoryController_getBeanById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 원두 기록 ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 에스프레소 원두 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EspressoBeanResponseDto"];
        };
      };
      /** @description 해당 원두 기록이 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GameController_createResult: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameHistoryDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
    };
  };
  GameController_getPokeLoungeState: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeStateResponseDto"];
        };
      };
      /** @description 저장된 Poke Lounge 상태가 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GameController_savePokeLoungeState: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavePokeLoungeStateDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeStateResponseDto"];
        };
      };
    };
  };
  GameController_getRanking: {
    parameters: {
      query: {
        /** @description 조회할 게임 타입 */
        gameType: components["schemas"]["GameType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameRankingHistoryDto"][];
        };
      };
    };
  };
  GameController_getGameResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공유된 게임 결과 조회 (로그인 필요 없음) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameHistoryResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_createRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_getRoom: {
    parameters: {
      query: {
        nowMs: string;
        afterRevision?: number;
      };
      header?: never;
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_bindCompetitiveSeat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BindCompetitiveSeatDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompetitiveAssignmentResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_submitCompetitiveAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomCode: string;
        matchId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitCompetitiveActionDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompetitiveActionResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_joinRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinPokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_setReady: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPokeLoungeReadyDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_updatePartySnapshot: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePokeLoungePartySnapshotDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_submitResult: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitPokeLoungeMatchResultDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_leaveRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeavePokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomResponseDto"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  RecipeController_getRecipes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 레시피 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeResponseDto"][];
        };
      };
    };
  };
  RecipeController_getRecipeById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 레시피 UUID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 레시피 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeResponseDto"];
        };
      };
      /** @description 레시피 ID가 UUID 형식이 아님 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 해당 레시피가 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ResumeRagController_chat: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeRagChatRequestDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResumeRagChatResponseDto"];
        };
      };
      /** @description 허용된 VSCoke 웹 origin이 아닌 요청 */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WordleController_getRandomWord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 랜덤으로 선택된 5글자 영단어 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WordResponseDto"];
        };
      };
    };
  };
  WordleController_checkWord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckWordDto"];
      };
    };
    responses: {
      /** @description 단어 존재 여부 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckWordResponseDto"];
        };
      };
    };
  };
}
